name: Build Native Addon

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm i

      - name: Build for macOS
        run: |
          cd frontwindow
          make build-macos

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontwindow-macos
          path: frontwindow/build/darwin/frontwindow.node
          retention-days: 30

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm i

      - name: Setup Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.1

      - name: Build for Windows
        run: |
          cd frontwindow
          make build-win
        env:
          NODE_INCLUDE: ${{ env.NODE_INCLUDE }}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontwindow-windows
          path: frontwindow/build/windows/frontwindow.node
          retention-days: 30
